name: Release CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  todoapp-ci:
    name: Todoapp CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Verify dependencies
        run: go mod verify
